### PR TITLE
Add trainer titles for "担当", "専属", and "名手"

### PR DESCRIPTION
**Pull request by sasigume**
These titles indicate how many fans you have for a specific character. Kanji words are often confusing even for Japanese speaker like me

|Trainer title|Condition|My translation|Other meaning(s)|
|---|---|---|---|
|(Horse name)担当|Get 10M fans|(Horse name)'s Personal Trainer|being in charge|
|(Horse name)専属|Get 50M fans|(Horse name)'s Exclusive Trainer|attached to; specialist|
|(Horse name)名手|Get 100M fans|(Horse name)'s Best Trainer|master; expert|

"名手" is usually translated as "master", but "Master of (Horse name)" doesn't fit Uma Musume world, it sounds like FGO lol

### CODE REVIEW

**Comment by robflop** [comment]
I like your translation of 担当 here.

名手 as "Best Trainer" sounds a bit off imo, but i wouldn't know what to use in exchange, since as you noted "Master" sounds like FGO, lol.

For 専属, what do you think about using the other meaning "Specialist", as noted in your post (E.g. "Vodka Specialist")?

I somewhat feel like "Personal Trainer" already implies "Exclusive Trainer", so if "Specialist" also works that may be better ot use here.

**Comment by FabulousCupcake** [comment]
Meister Trainer? 🤔  
IMO `Vodka Master Trainer` is totally OK. `Master of Vodka` or `Vodka Master` definitely not, as you said there's FGO vibes lol.

> I somewhat feel like "Personal Trainer" already implies "Exclusive Trainer", so if "Specialist" also works that may be better ot use here.

I disagree somewhat; personal trainer doesn't imply exclusivity (in the sense that you can have multiple personal trainer for different trainings), but I'm not against `Vodka Specialist` either. `Vodka Specialist Trainer`? 🤔

**Comment by robflop** [comment]
Going for the german "Meister" imo just pushes the problem into another language :P

Another idea is that we transform 名手 into an adjective as opposed to a noun, i.e. "Masterful" instead of "Master".
We could then go with e.g. "Masterful Vodka Trainer", which sounds idiomatic, stays accurate and doesn't have FGO vibes.

> I disagree somewhat; personal trainer doesn't imply exclusivity (in the sense that you can have multiple personal trainer for different trainings)

Ah yea, that's true as well. I think "Exclusive Trainer" sounds a lot more clean so if there's no overlap in meaning i'd prefer that.

Regarding the "Specialist" suggestion though, how about using again going for an adjective as opposed to a noun here, e.g. "Vodka-specialized Trainer", maybe?

**Comment by FabulousCupcake** [comment]
I have nothing against Best Trainer as well btw; we can merge this PR as is.  
@robflop please send request changes if you feel that it should be `masterful trainer`

**Review by robflop — CHANGES_REQUESTED** [review]
Copied from above comments:

名手 as "Best Trainer" sounds a bit off imo, how about transforming 名手 into an adjective as opposed to a noun, i.e. "Masterful" instead of "Master"?

We could then go with e.g. "Masterful Vodka Trainer", which sounds idiomatic, stays accurate and doesn't have FGO vibes.

**Comment by sasigume** [comment]
Thanks for suggesting. I'm working on it

**Review by robflop — APPROVED** [review]

**Comment by FabulousCupcake** [comment]
Thank you 🙇

**Comment by robflop** [comment]
Same from me, great to have a native speaker of Japanese helping with these titles.
Had been been struggling with em for a while.

**Pull request merged**
