### PR TITLE
Update miscellaneous.csv

### PR DESCRIPTION
**Pull request by chrisforyst**
Adding categories 8, 31/34, 35, 121, 138

### CODE REVIEW

**Comment by FabulousCupcake** [comment]
Could you also update [NOTES.md](https://github.com/FabulousCupcake/umamusume-db-translate/blob/master/NOTES.md) with the new misc categories?

**Comment by chrisforyst** [comment]
Okay. I have it prepared. Is there an option to add it also to the same commit?

**Comment by FabulousCupcake** [comment]
Not necessary to put it in a single commit, but yes it's possible to modify past commits with `--amend` flag.  
Or alternatively by running `git rebase --interactive` against the base branch (`FabulousCupcake:master`) in this case, which will then allow you to `edit` or `fixup` (combine the commit with previous one) the commits.

**Review by FabulousCupcake — APPROVED** [review]

**Comment by FabulousCupcake** [comment]
Thank you 🙇

**Pull request merged**
